export function newRx({ id = 'synthetic-msg-1', pon = 'DEMO-PON-1', directions = 'Give 1 tablet by mouth two times a day for example symptoms', sentTime = '2026-10-02T04:00:00Z', times = ['0900', '2100'] } = {}) {
  return `<Message TransactionVersion="20170715"><Header><From>DEMO-SENDER</From><To>DEMO-PHARMACY</To><MessageID>${id}</MessageID><SentTime>${sentTime}</SentTime><PrescriberOrderNumber>${pon}</PrescriberOrderNumber><Security><UsernameToken><Password>never-export-this</Password></UsernameToken></Security></Header><Body><NewRx><Facility><Identification><FacilityID>DEMO-SITE</FacilityID></Identification><FacilityName>Example &amp; Co</FacilityName></Facility><Patient><HumanPatient><Identification><MedicalRecordIdentificationNumberEHR>DEMO-RESIDENT</MedicalRecordIdentificationNumberEHR><SocialSecurity>never-use-this</SocialSecurity></Identification></HumanPatient></Patient><MedicationPrescribed><DrugDescription>Example 0.5 MG Tablet</DrugDescription><DrugCoded><ProductCode><Code>11111222233</Code><Qualifier>ND</Qualifier></ProductCode><Strength><StrengthValue>0.5</StrengthValue></Strength></DrugCoded><Sig><SigText>${directions}</SigText><Instruction><DoseAdministration><Dosage><DoseQuantity>1</DoseQuantity><DoseUnitOfMeasure><Text>tablet</Text></DoseUnitOfMeasure></Dosage><RouteOfAdministration><Text>oral route</Text></RouteOfAdministration></DoseAdministration><TimingAndDuration><Frequency><FrequencyNumericValue>2</FrequencyNumericValue><FrequencyUnits><Text>day</Text></FrequencyUnits></Frequency></TimingAndDuration><IndicationForUse><Indication><Text>Unspecified</Text></Indication></IndicationForUse></Instruction></Sig>${times.map(time => `<FacilitySpecificHoursOfAdministrationTiming><HoursOfAdministrationValue>${time}</HoursOfAdministrationValue></FacilitySpecificHoursOfAdministrationTiming>`).join('')}<OtherMedicationDate><OtherMedicationDate><DateTime>2026-10-02T13:00:00Z</DateTime></OtherMedicationDate><OtherMedicationDateQualifier>StartDate</OtherMedicationDateQualifier></OtherMedicationDate></MedicationPrescribed></NewRx></Body></Message>`;
}
export const escapeXml = (text: string) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
export function fourLogHar() {
  const xml = newRx();
  const fill = `<Message><Header><From>DEMO-PHARMACY</From><MessageID>synthetic-fill</MessageID><RelatesToMessageID>synthetic-msg-1</RelatesToMessageID><PrescriberOrderNumber>DEMO-PON-1</PrescriberOrderNumber></Header><Body><RxFill><MedicationDispensed><DrugDescription>Different dispensed brand</DrugDescription><Sig><SigText>Pharmacy directions</SigText></Sig></MedicationDispensed><MedicationPrescribed><DrugDescription>Example 0.5 MG Tablet</DrugDescription><Sig><SigText>Original directions</SigText></Sig></MedicationPrescribed></RxFill></Body></Message>`;
  const records = [
    { position: '101', channel: 'MessageBroker', type: 'Info', payload: `Raw incoming data: POST /ProcessMessage HTTP/1.1<br>\n${escapeXml(xml)}` },
    { position: '102', channel: 'MessageBroker', type: 'Info', payload: `Request Message: &lt;soap:Envelope&gt;&lt;SendMessage&gt;${escapeXml(escapeXml(xml))}&lt;/SendMessage&gt;&lt;/soap:Envelope&gt;` },
    { position: '103', channel: 'Paxit: Demo - FW Outbound', type: 'Message', payload: 'MSH|^~\\&amp;|FRAMEWORK|||||||RDE^O11<br>RXO|example' },
    { position: '104', channel: 'MessageBroker', type: 'Info', payload: escapeXml(fill) },
  ];
  const list = records.map(r => `addRowReverse({\nPosition: '${r.position}',\nDate: '2026/10/02',\nType: '${r.type}',\nChannel: '${r.channel}',\nMessageId: '20261002-${r.position}',\nRefMsgId: '20261002-100'\n});`).join('\n');
  return { log: { entries: [
    { request: { url: 'http://example.invalid/log_entries' }, response: { status: 200, content: { text: list } } },
    ...records.map(r => ({ request: { url: 'http://example.invalid/log_view_entry', postData: { params: [{ name: 'Position', value: r.position }, { name: 'Date', value: '2026/10/02' }] } }, response: { status: 200, content: { encoding: 'base64', text: btoa(JSON.stringify({ Message: r.payload, DisplayMode: 'Formatted', StartLineOffset: 0, CountOfLines: 1, TotalCountOfLines: 1 })) } } })),
  ] } };
}
