"""Compile the root SIG list into offline indication/duration lookups."""
import argparse
import hashlib
import json
import re
from pathlib import Path
from xml.etree import ElementTree as ET
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'Sig Codes (searchable) (1).docx'
TARGET = ROOT / 'src/lib/clinical/sigCodeReference.ts'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
ns = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
with ZipFile(SOURCE) as archive:
    document = ET.fromstring(archive.read('word/document.xml'))
codes = {}
for row in document.findall('.//' + ns + 'tr'):
    cells = [' '.join(t.text or '' for t in cell.findall('.//' + ns + 't')).strip()
             for cell in row.findall(ns + 'tc')]
    if len(cells) >= 2 and max(map(len, cells)) < 1000 and cells[0]:
        code, expansion = cells[:2]
        if expansion.upper().startswith('FOR ') and not re.match(r'^FOR \d', expansion):
            codes[code] = expansion.upper()
        elif re.fullmatch(r'X\d+(?:D|W|WK|M|H)|Q\d+H|QDQ\d+D|\d+[TCG]', code) or code in {
            'X1', 'SSW', 'SSP', '1V', 'NEB', 'INH', 'OS', 'OD', 'OU',
            'LT', 'RT', 'BIDAC', 'TIDAC', 'QIDAC', 'QDAC', 'AC', 'AP4GM',
            '1RS', '2RS', '1LOZ', '3G', '4G', '5G', 'AL', 'AD', 'AU', 'PV', 'PR', 'SL', 'PO/SL',
            'QDQ2D', 'QOD', 'WMQD', 'WMBID', 'WMTID', 'WM', 'TAW', 'LOR1MG',
            'QD', 'BID', 'TID', 'QID', 'QAM', 'QPM', 'QHS', 'PO', 'GT', 'PEGT', 'JT', 'NG',
            'SQ', 'IM', 'INJ', 'UN', 'DIS', 'ENOS', '1SP', '2SP', 'ACHS', 'NTE4', '3GM', '3GME',
        }:
            codes[code] = expansion.upper()
content = ('// Generated by scripts/generate-clinical-code-reference.py; do not edit.\n'
           f'// Source: {SOURCE.name}\n'
           f'// SHA256: {hashlib.sha256(SOURCE.read_bytes()).hexdigest()}\n'
           'export const SIG_CODE_REFERENCE: Readonly<Record<string, string>> = '
           + json.dumps(dict(sorted(codes.items())), indent=2, ensure_ascii=False) + ';\n')
if args.check:
    if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != content:
        raise SystemExit('Clinical SIG lookup differs from the root reference. Run the generator.')
    print(f'Clinical SIG lookup matches root reference ({len(codes)} codes)')
else:
    TARGET.write_text(content, encoding='utf-8', newline='\n')
    print(f'Generated {len(codes)} verified clinical codes')
